export type MaterialNames =
  | "metalBlue"
  | "metalPurple"
  | "gold"
  | "copper"
  | "aluminum"
  | "iron"
  | "castIron"
  | "steel"
  | "whitePlastic"
  | "greenPlastic"
  | "pearl"
  | "bubble"
  | "cyber"
