import {
  AdditiveBlending,
  Color,
  DoubleSide,
  type MeshPhysicalMaterialParameters,
} from "three"
import type { MaterialNames } from "./MaterialNames"

export const physicalMatParamLib: {
  [K in MaterialNames]: MeshPhysicalMaterialParameters
} = {
  metalPurple: {
    color: 0xdd11ff,
    metalness: 1,
    roughness: 0.35,
    sheen: 1,
    sheenColor: 0xff0fa7,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.2,
    iridescenceIOR: 2,
    anisotropy: 0.125,
  },

  metalBlue: {
    color: 0x1144ff,
    metalness: 1,
    roughness: 0.35,
    sheen: 1,
    sheenColor: 0x0000ff,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.2,
    iridescenceIOR: 2,
    anisotropy: 0.125,
  },

  gold: {
    color: 0xffd711,
    metalness: 1,
    roughness: 0.35,
    sheen: 1,
    sheenColor: 0xffa70f,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.2,
    iridescenceIOR: 2,
    anisotropy: 0.125,
  },

  copper: {
    color: 0xb87333,
    metalness: 1,
    roughness: 0.4,
    sheen: 1,
    sheenColor: 0x449922,
    clearcoat: 0,
    clearcoatRoughness: 0.15,
    iridescence: 0.3,
    iridescenceIOR: 1.5,
    anisotropy: 0.75,
    anisotropyRotation: 1,
  },

  aluminum: {
    color: 0xcccccc,
    metalness: 1,
    roughness: 0.3,
    sheen: 0,
    sheenColor: 0xffa70f,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.25,
    iridescenceIOR: 2,
    anisotropy: 0.5,
  },

  iron: {
    color: 0x43464b,
    metalness: 1,
    roughness: 0.6,
    sheen: 1,
    sheenColor: 0xffa70f,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.2,
    iridescenceIOR: 2,
    anisotropy: 0.125,
  },

  castIron: {
    color: 0x222222,
    metalness: 1,
    roughness: 0.8,
    sheen: 0.25,
    sheenColor: 0xffa70f,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.2,
    iridescenceIOR: 2,
    anisotropy: 0.125,
  },

  steel: {
    color: 0x8c8c8c,
    metalness: 1,
    roughness: 0.3,
    sheen: 0,
    sheenColor: 0xffa70f,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
    iridescence: 0.25,
    iridescenceIOR: 2,
    anisotropy: 0.5,
  },

  whitePlastic: {
    color: 0xffffff,
    metalness: 0,
    roughness: 0.25,
    sheen: 1,
    sheenColor: 0xffffff,
    clearcoat: 1,
    clearcoatRoughness: 0.25,
  },

  greenPlastic: {
    color: 0x11ff11,
    metalness: 0,
    roughness: 0.25,
    sheen: 1,
    sheenColor: 0xffffff,
    clearcoat: 1,
    clearcoatRoughness: 0.25,
  },

  pearl: {
    color: new Color(2, 2, 2),
    metalness: 0.2,
    roughness: 0.55,
    sheen: 1,
    sheenColor: 0xffa7af,
    clearcoat: 1.82,
    clearcoatRoughness: 0.3,
    iridescence: 2,
    iridescenceIOR: 2,
  },

  bubble: {
    color: new Color(0, 0, 0),
    metalness: 1,
    roughness: 0.5,
    sheen: 0.5,
    sheenColor: 0xffa7af,
    clearcoat: 1,
    clearcoatRoughness: 0.8,
    iridescence: 2,
    iridescenceIOR: 1.2,
    depthWrite: false,
    side: DoubleSide,
    blending: AdditiveBlending,
    transparent: true,
    opacity: 0.2,
  },

  cyber: {
    color: new Color(0, 0.5, 1),
    metalness: 0,
    roughness: 0.5,
    sheen: 0.5,
    sheenColor: 0xffa7af,
    iridescence: 2,
    iridescenceIOR: 1.2,
    emissive: new Color(0, 0.25, 0.5),
    wireframe: true,
  },
} as const
